repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: debug-statements
      - id: check-docstring-first

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml"]
        additional_dependencies: ["bandit[toml]"]

  # MyPy disabled for initial infrastructure phase - will be enabled in Phase 2
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.8.0
  #   hooks:
  #     - id: mypy
  #       additional_dependencies: []
  #       args: [--ignore-missing-imports, --no-strict-optional]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.10
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: uv run pytest
        additional_dependencies: ["uv", "pytest"]
        language: python
        pass_filenames: false
        always_run: true
      - id: generate_docs
        name: generate docs
        entry: uv run sphinx-build
        additional_dependencies: ["uv", "sphinx"]
        args: [-M, html, docs/source, docs/build]
        language: python
        pass_filenames: false
        files: ^docs/
