language: python

before_install:
  - pip install sphinx==3.1.1
  - pip install travis-sphinx

python:
  - "3.7"
script:
  - pip install .
  - pytest tests
  - mkdir doc
  - mkdir doc/build
  - cp -r images docs/source
  - travis-sphinx build

after_success:
  - travis-sphinx deploy --branches=master --verbose

deploy:
  provider: pypi
  username: "__token__"
  password:
    secure: "hEebsXpQBRI1voIZx6xKSxuPEXAteJJsAIQ6WBta09FLNoCuxExLLv03e3iAh9lr8NJJa0pCqQ/edId2KJszab4oEvBSKd0oKeK4+VZ0Z3sFO4NgyjNjXsZsizmSjRKIbjS7miybVcMWmDqeiblYLBTMDq/+34RQDS79IjFlzWsu6RPqJCC0wum+QETOR5rfzYCKTYjwOHJ+IBzqTbF4/VmQmWyMZZTX+BCi6PhmxMsBVNUS8QRS0g778GKwpYfUaNX+z/hLtH9duvRehimoth3eW3+gAQCA+1f5OAyLB8u+mFg3XfTSVtDPU5Q6sSz52zZXpCMKpsUiJdwdgJnP3kDinorUrlmFJbpjqZpnJ2csuqOywXEBMGeiJL34STRTdRbJYTFR4p4lr12VCYf/O6riRdtqAjAKzZOzwLtUN7YrFuaZSF/NgyGr0L2j+/SO+vyswAhEDqZeNbvHsPxEF6v/hnaE9ZdTMSlIm9huxi4Q5mqyoe8HbaEBNW4HvuzftxBUZHbnvPxWnI0UyHldVcazrJ104a92yaglAzbI0gMRTYojwXKCw4as36DTHL42fyk0hGZlj7DewC9sAJYV7lUSfX/LcapynDdFGsIBWpnZf9Zha2Ql/1nVAkp7GXBNX7ngIyr48qLX9XwmZpou2ZkjxrRLaZlurf1vMN+LsbA="
  on:
    branch: master
  skip_cleanup: true

