language: python
#python:
#  - "3.6"      # current detault Python on Travis CI
#  - "3.7"
## command to install dependencies
#install:
#  - pip install -r requirements.txt
## command to run tests
#script:
#  - pytest
script:
- echo "skipping tests"

deploy:
  provider: pypi
  user: bbrenninkmeijer
  password:
    secure: FyoqedUJBvMh+/vZj1qoPxKXeTZ8968ZVDZKvaG2YhC3Kw0hkzH/Q6MPogd/oS5pcY/p4+YXRjGN++gD8OpPf27q9R+8Eh8nYxLYp02N1CDqDk8YsQVQfYeudodBfx+U8o6JeT00Qw5Tpi/vpSV4rz2Ubwipm2ktH/8SUGahSqVSOHFthqTcEjfPc9OD8ljBmn54hImKiQw2UqgnqMrovM4cNgcmpIXFx6sA8xbXe3F7pgP6rSIQYWvCfQ7y5oDAZwdN6Z1QRelZOpEZ1Nj3UDMXuBIiW4C7FHaqtEMdtBmTc6wVaE7+FbD4p8nTql+KFe42Nw6OAWFWHr7Z8obTR7wGYLXeN2VyinF1rLiOGFrupJxagiZRKN/zEPFK3JJmbHMT9vLizfjAdhHRb63uQxNjNJGYYLyLNrbEo8Yvy9R+6QsF7eyXFRVBB9rfWvhdx2rThUx8OaQCu0tsZY1zhy4opD1pZQu1Hy/SvKvfRjXHTtncvgjg0aSsqtnFb5J3RmpAXYs3xfiq+RWbLoMxxcVeQIJz4CYyWyptu6NNmvUavLQfswQqVuLw7y7X/FUEGc98isL4VhC1J7A5PwOIBUUJ5ShiPJXclyEwJJUlZwQfMbuXHVjnXV/NEvyDQ15W3hqdbGRwfsq84BSJFyIOSrgq7hPal8pEXSQbh1dj2Wg=
  on:
#    tags: true
    branch: production
