name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - baukebrenninkmeijer
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen? Please make sure you are using the latest software.
      placeholder: Tell us what you see!
      # value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      placeholder: Please add versions of matplotlib, seaborn, pandas and dython.
      value: |
        Please run the following commands:
        ```
        import sys, dython, matplotlib, seaborn, table_evaluator
        print(sys.version_info)
        print(dython.__version__)
        print(matplotlib.__version__)
        print(seaborn.__version__)
        print(table_evaluator.__version__)
        ```
    validations:
      required: true
  - type: textarea
    id: errormessages
    attributes:
      label: Relevant log output or error messages
      description: Please copy and paste any relevant log output or error messages. This will be automatically formatted into code, so no need for backticks.
      render: shell
