name: Automatic Semantic Versioning

on:
  workflow_run:
    workflows: ["Code Quality and Security Check"]
    types:
      - completed
    branches:
      - master

jobs:
  version-and-tag:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get latest tag
        id: get_latest_tag
        run: |
          LATEST_TAG=$(git tag --sort=-version:refname | head -n 1)
          if [ -z "$LATEST_TAG" ]; then
            LATEST_TAG="0.0.0"
          fi
          echo "latest_tag=$LATEST_TAG" >> $GITHUB_OUTPUT
          echo "Latest tag: $LATEST_TAG"

      - name: Get commits since last tag
        id: get_commits
        run: |
          COMMITS=$(git log ${{ steps.get_latest_tag.outputs.latest_tag }}..HEAD --oneline --pretty=format:"%s")
          echo "commits<<EOF" >> $GITHUB_OUTPUT
          echo "$COMMITS" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Determine version bump
        id: version_bump
        run: |
          COMMITS="${{ steps.get_commits.outputs.commits }}"
          MAJOR=false
          MINOR=false
          PATCH=false

          echo "Analyzing commits:"
          echo "$COMMITS"

          # Check for breaking changes (major version)
          if echo "$COMMITS" | grep -qE "(BREAKING CHANGE|!:)"; then
            MAJOR=true
            echo "Found breaking changes - major version bump"
          fi

          # Check for features (minor version)
          if echo "$COMMITS" | grep -qE "^feat(\(.+\))?:"; then
            MINOR=true
            echo "Found features - minor version bump"
          fi

          # Check for fixes (patch version)
          if echo "$COMMITS" | grep -qE "^fix(\(.+\))?:"; then
            PATCH=true
            echo "Found fixes - patch version bump"
          fi

          # Determine version bump type
          if [ "$MAJOR" = true ]; then
            echo "bump_type=major" >> $GITHUB_OUTPUT
          elif [ "$MINOR" = true ]; then
            echo "bump_type=minor" >> $GITHUB_OUTPUT
          elif [ "$PATCH" = true ]; then
            echo "bump_type=patch" >> $GITHUB_OUTPUT
          else
            echo "bump_type=none" >> $GITHUB_OUTPUT
          fi

      - name: Calculate new version
        id: new_version
        if: steps.version_bump.outputs.bump_type != 'none'
        run: |
          CURRENT_VERSION="${{ steps.get_latest_tag.outputs.latest_tag }}"
          BUMP_TYPE="${{ steps.version_bump.outputs.bump_type }}"

          # Parse current version
          if [[ $CURRENT_VERSION =~ ^v?([0-9]+)\.([0-9]+)\.([0-9]+) ]]; then
            MAJOR=${BASH_REMATCH[1]}
            MINOR=${BASH_REMATCH[2]}
            PATCH=${BASH_REMATCH[3]}
          else
            MAJOR=0
            MINOR=0
            PATCH=0
          fi

          # Increment version based on bump type
          case $BUMP_TYPE in
            major)
              MAJOR=$((MAJOR + 1))
              MINOR=0
              PATCH=0
              ;;
            minor)
              MINOR=$((MINOR + 1))
              PATCH=0
              ;;
            patch)
              PATCH=$((PATCH + 1))
              ;;
          esac

          NEW_VERSION="$MAJOR.$MINOR.$PATCH"
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "New version: $NEW_VERSION"

      - name: Create and push tag
        if: steps.version_bump.outputs.bump_type != 'none'
        run: |
          NEW_VERSION="${{ steps.new_version.outputs.new_version }}"

          echo "Creating tag: $NEW_VERSION"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git tag -a "$NEW_VERSION" -m "chore: release version $NEW_VERSION

          Auto-generated by semantic versioning workflow based on conventional commits."

          git push origin "$NEW_VERSION"

          echo "✅ Successfully created and pushed tag: $NEW_VERSION"

      - name: No version bump needed
        if: steps.version_bump.outputs.bump_type == 'none'
        run: |
          echo "ℹ️ No conventional commits found that warrant a version bump."
          echo "Commits since last tag contain only non-versioned changes (docs, chore, etc.)"
