name: Publish documentation

on:
  push:
    branches:
      - master
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: docs
    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: docs/build/html
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

