name: Run tests
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8',  '3.9', '3.10']
    name: Python ${{ matrix.python-version }} sample
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: install_dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest
        pip install .
    - name: Run tests
      run: |
        pytest tests
